### ISSUE TITLE
examples?

### ISSUE THREAD

**Issue by Kreijstal** [jneug/typst-finite#3]
do you have a typst with lots of examples?

**Comment by jneug** [comment]
Hi there. Positioning states is pretty straightforward, as @Jakob-Ziechmann showed. Just provide a dict with the states as names and the CeTZ coordinates as values.

Finite ships with some more dynamic layouts, that work with different state styles and still try to position states with different sizes in a specific way. In your case, you could use the grid layout like this:

```typst
#import "@preview/finite:0.3.0": automaton, layout

#let aut = (
  q0: (q1: "b", q3: "a"),
  q1: (q1: "b", q2: "a"),
  q2: (q1: "b"),
  q3: (q3: "a,b"),
)

#let style = (
  q0-q1: (curve: 0),
  q0-q3: (curve: 0),

  q3-q3: (anchor: bottom)
)

#automaton(
  aut,
  layout: layout.grid.with(columns: 3, spacing: (2, -4)),
  style: style,
)
```

The result should look just about like your example.

----

I could properly maintain finite in the second half of 2023, since my work schedule didn't leave much spare time, but I hope to update finite in the near future. I will then add more examples and an updated manual.
